import Head from "next/head";
import Image from "next/image";
import { Poppins } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function Home() {
  let [isNavOpen, setIsNavOpen] = useState(false);

  function handleHamburger(e) {
    setIsNavOpen(!isNavOpen);
    console.log(isNavOpen);
  }
  return (
    <>
      <Head>
        <title>CV TOCHLER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          type="module"
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        ></script>
        <script
          defer
          nomodule
          src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        ></script>
      </Head>
      <main
        className="min-h-screen w-full block bg-[#F5DEB3]"
        style={poppins.style}
      >
        {/* Navbar */}
        <nav className="p-5 z-[1000] bg-[#0B142E] isolate relative shadow flex justify-between items-center">
          <div>
            <span className="text-2xl text-[#00FFFF] hp:text-base">
              Tochler Suputra
            </span>
          </div>
          <span
            onClick={handleHamburger}
            className="text-3xl text-[#00FFFF] cursor-pointer mx-2  md:hidden block"
          >
            <ion-icon name="menu"></ion-icon>
          </span>

          <ul
            className={`nav__items text-[#00FFFF] hp:text-[#FF1493]  hover:text-cyan-500  hp:z-[-1]  hp:bg-[#0B142E] transition-all duration-500 flex gap-2 hp:w-full hp:absolute left-0 right-0  hp:flex-col px-4 ${
              isNavOpen ? "hp:top-full hp:opacity-100" : "hp:opacity-0 top-0"
            }`}
          >
            {/* Project */}
            <li className="mx-4 md:my-0">
              <a
                href="#about"
                className="text-xl hover:text-white duration-500"
              >
                ABOUT
              </a>
            </li>
            {/* Line */}
            <li className="mx-5 md:my-0 grid place-items-center">
              <div className="h-7 w-[2px] hp:hidden bg-[#00FFFF]"></div>
            </li>
            {/* Resume */}
            <li className="mx-4 md:my-0">
              <a
                href="#resume"
                className="text-xl  hover:text-white duration-500"
              >
                RESUME
              </a>
            </li>
            {/* Line */}
            <li className="mx-5 md:my-0 grid place-items-center">
              <div className="h-7 w-[2px] hp:hidden bg-[#00FFFF]"></div>
            </li>
            {/* Contact */}
            <li className="mx-4 md:my-0">
              <a
                href="#contact"
                className="text-xl  hover:text-white duration-500"
              >
                CONTACT
              </a>
            </li>
            <h2 className=""></h2>
          </ul>
        </nav>

        {/* about */}
        <div id="about" className="relative">
          <div className="flex justify-center">
            <div className="hp:flex-col flex flex-row w-[70%] mt-10 bg-[#0B142E]">
              <div>
                <img
                  className="w-[150%] h-[100%] object-cover"
                  src="assets/seklh2.jpg"
                ></img>
              </div>
              <div className="w-[50%] hp:w-full flex flex-col justify-center p-4 h-[100%] pl-9 pt-7">
                <p className="text-[45px] hp:text-3xl text-white font-bold">
                  Tochler Suputra
                </p>
                <p className="text-[35px] hp:text-xl text-white font-medium">
                  PROJECT CV
                </p>
                <p className="text-white mt-5">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Veniam illo quia facilis cumque perspiciatis, ducimus
                  praesentium reprehenderit dolores vitae voluptatibus alias,
                  magni impedit, autem architecto illum voluptates omnis
                  repudiandae ipsum. Lorem ipsum dolor sit amet, consectetur
                  adipisicing elit. Doloribus libero optio deserunt voluptatem
                  sit cumque tempora, omnis nobis facere inventore doloremque
                  blanditiis nam velit, aut temporibus, nemo labore! Cum,
                  dignissimos.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Resume */}

        <div id="resume" className="ml-[0px] mt-20">
          <p className="border-b-4 border-pink-600 text-3xl w-min mx-auto font-bold mb-10">
            RESUME
          </p>
          <div className="container relative isolate w-[85%] mx-auto justify-center flex flex-col min-h-screen items-center gap-6">
            <div className="line__down hp:hidden absolute left-1/2 top-0 z-[-1] -translate-x-full h-full w-2 bg-slate-400"></div>

            <div className="w-full grid grid-cols-5 hp:flex hp:flex-col mx-auto grid-rows-1 gap-6">
              <div className="w-full p-16 col-span-3 relative isolate h-[100%] flex items-center">
                <div className="absolute left-0 top-0 right-1/2 bottom-0 bg-orange-800 z-[-1]"></div>
                <img
                  className="h-full w-full aspect-[16/10] object-cover"
                  src="assets/Wh.jpg"
                ></img>
              </div>
              <div className="w-full col-span-2 my-auto text-[30px] mr-[450px]">
                <p className=" flex font-bold text-4xl text-black">
                  SDN 2 SERANGAN
                </p>
                <p className="text-black hp:text-2xl text-2xl">
                  Sekolah Dasar Negri
                </p>
                <p className="text-black hp:text-2xl text-2xl">2012-2018</p>
                <p className=" flex items-center text-black text-left hp:text-xl text-xl">
                  Jl. Tukad Semanik, Serangan, Denpasar Selatan, Kota Denpasar,
                  Bali 80229
                </p>
              </div>
            </div>

            <div className="w-full grid grid-cols-5 hp:flex hp:flex-col-reverse mx-auto grid-rows-1 gap-6">
              <div className="w-full col-span-2 my-auto text-[30px] mr-[450px]">
                <p className=" flex font-bold text-4xl text-black">
                  SMP DHARMA WIWEKA
                </p>
                <p className="text-black hp:text-2xl text-2xl">
                  Sekolah Menengah Pertama
                </p>
                <p className="text-black hp:text-2xl text-2xl">2018-2021</p>
                <p className=" flex items-center text-black text-left hp:text-xl text-xl">
                  Jl. Pulau Moyo I No.5, Pedungan, Denpasar Selatan, Kota
                  Denpasar, Bali 80222
                </p>
              </div>
              <div className="w-full p-16 col-span-3 relative isolate h-[100%] flex items-center">
                <div className="absolute left-1/2 top-0 right-0 bottom-0 bg-neutral-400 z-[-1]"></div>
                <img
                  className="h-full w-full aspect-[16/10] object-cover"
                  src="assets/Dharma.jpg"
                ></img>
              </div>
            </div>
            <div className="w-full grid grid-cols-5 hp:flex hp:flex-col mx-auto grid-rows-1 gap-6">
              <div className="w-full p-16 col-span-3 relative isolate h-[100%] flex items-center">
                <div className="absolute left-0 top-0 right-1/2 bottom-0 bg-neutral-800 z-[-1]"></div>
                <img
                  className="h-full w-full aspect-[16/10] object-cover"
                  src="assets/gedung.jpg"
                ></img>
              </div>
              <div className="w-full col-span-2 my-auto text-[30px] mr-[450px]">
                <p className=" flex font-bold text-4xl text-black">
                  SMK TI BALI GLOBAL
                </p>
                <p className="text-black hp:text-2xl text-2xl">
                  Sekolah Menengah Kejuruan
                </p>
                <p className="text-black hp:text-2xl text-2xl">2021-Sekarang</p>
                <p className=" flex items-center text-black text-left hp:text-xl text-xl">
                  Jl. Tukad Citarum No.44, Dauh Puri Klod, Denpasar Selatan,
                  Kota Denpasar, Bali 80234
                </p>
              </div>
            </div>
          </div>

          {/* <div className="flex flex-col justify-center gap-[20px]">
            <p className="text-3xl font-extrabold">Bahasa</p>
            <div className="flex flex-col gap-8 ml-[60px]">
              <div className="flex flex-row gap-5">
                <div className="triangle self-center"></div>
                <p className="text-3xl font-semibold">Bahasa Indonesia</p>
              </div>
              <div className="flex flex-row gap-5">
                <div className="triangle self-center"></div>
                <p className="text-3xl font-semibold">Bahasa Bali</p>
              </div>
            </div>
          </div> */}
        </div>

        {/* contact */}
        <div id="contact" className="mt-20">
          <div className="flex flex-col mx-auto w-[70%] hp:w-[90%] p-6 bg-[#0B142E]">
            <div className="flex justify-center hp:flex-col items-center ">
              <div className="w-1/2 hp:w-full px-4">
                <div className="mx-auto text-center mb-16">
                  <h4 className="font-semibold text-lg text-white mb-2 ">
                    Contact
                  </h4>
                  <h2 className="font-bold text-white text-3xl mb-4 sm:text-4xl lg:text-5xl">
                    Call Me
                  </h2>
                  <p className="font-medium text-md text-white md:text-lg">
                    you can contact me via the form that I have provided
                  </p>
                  <div className="flex justify-center items-center gap-4 text-white text-[30px]">
                    <a href="https://www.instagram.com/invites/contact/?i=ogfm8wqi7mtg&utm_content=nmrmqby">
                      <ion-icon
                        name="logo-instagram"
                        className="w-[100%] h-[50px]"
                      ></ion-icon>
                    </a>
                    <a href="http://wa.me/6288987251020">
                      <ion-icon
                        name="logo-whatsapp"
                        className="w-[100%] h-[50px]"
                      ></ion-icon>
                    </a>
                  </div>
                </div>
              </div>

              <form
                className="flex w-1/2 hp:w-full flex-col items-center"
                action="https://formsubmit.co/bapakmugantengx@gmail.com"
                method="post"
                autoComplete="off"
              >
                <div className="flex flex-col w-[100%] px-4 mb-8">
                  <label
                    for="name"
                    className="text-base font-bold text-[#00FFFF] self-center"
                  >
                    Nama
                  </label>
                  <input
                    type="text"
                    id="name"
                    className="w-[70%] hp:w-[100%] bg-slate-200 text-[#008b8b] p-3 rounded-md focus:outline-none self-center"
                    name="Nama"
                  />
                </div>
                <div className="flex flex-col w-[100%] px-4 mb-8">
                  <label
                    for="email"
                    className="text-base font-bold text-[#00FFFF] self-center"
                  >
                    Email
                  </label>
                  <input
                    type="text"
                    id="email"
                    className="w-[70%] hp:w-[100%] bg-slate-200 text-[#008b8b] p-3 rounded-md focus:outline-none self-center"
                    name="email"
                  />
                </div>
                <div className=" flex flex-col w-[100%] px-4 mb-8">
                  <label
                    for="massage"
                    className="text-base font-bold text-[#00FFFF] self-center"
                  >
                    Pesan
                  </label>
                  <textarea
                    type="text"
                    id="pesan"
                    className="w-[70%] hp:w-[100%] bg-slate-200 text-[#008b8b] p-3 rounded-md focus:outline-none h-32 self-center"
                    name="pesan"
                  ></textarea>
                </div>
                <div className="w-[90%] grid place-items-center px-4">
                  <button className="text-base text-semibold text-white bg-cyan-500 py-3 px-8 rounded-full w-1/2 hover:opacity-88 hover:shadow-lg">
                    Kirim
                  </button>
                </div>
                <input type="hidden" name="_captcha" value="false"></input>
              </form>
            </div>
          </div>
        </div>

        {/* footer */}
        <div class="bg-[#0B142E] text-center mt-12 lg:text-left flex justify-center items-center">
          <div className="text-gray-700 text-center p-4">
            {" "}
            <p class="text-[#00FFFF]">made by tochler</p>
          </div>
        </div>
      </main>
    </>
  );
}
